### ISSUE TITLE
Using with lldb on macOS Apple Silicon binary?

### ISSUE THREAD

**Issue by blacktop** [doronz88/hilda#3]
Can you please add an example of how to load hilda into a local lldb session?

Thank you!

**Comment by doronz88** [comment]
I've added [bare mode](https://github.com/doronz88/hilda#bare-mode) for opening an lldb shell where hilda is just loaded into lldb and you can attach and do everything in lldb yourself.

Also, every shell command executed is now printed so you can debug it or use the commands yourself.
In general to your question the command was:

```shell
command script import /path/to/lldb_entrypoint.py
```

**Comment by blacktop** [comment]
Wow! Thank you for such a fast turn-around!  I used it to do some tracing last night 👍 It helped me to understand more about the NEW dyld_shared_cache format on iOS15/macOS12
