### ISSUE TITLE
`monitor` and `callback`: wrong logic for functions with a large amount of arguments

### ISSUE THREAD

**Issue by yotka2** [doronz88/hilda#72]
The symbol monitor feature includes the following code:

`symbols_jar.py`:
```
def monitor(self, **args):
    ...
    if arg_count > 0:
        args_c['regs'] = {f'x{i + 2}': 'po' for i in range(arg_count)}
```
`hilda_client.py`:
```
def callback(hilda, frame, bp_loc, options):
    ...
    for name, fmt in options['regs'].items():
        value = hilda.symbol(frame.FindRegister(name).unsigned)
```
which works for functions with 8 arguments or less.

However, after 8 arguments, any further arguments are passed on the stack, so the current code starts printing gibberish.

Possible solutions are either to just print the registers `x0` up to `x7` and stop there,
or to read from the stack starting from the 9th argument.
A code that worked for me is something like
```
if (arg number < 8):
    return p.registers[x arg number]
return p.peek(p.registers.sp + 8 * (arg number - 9))
```
(using pseudocode because I'm not with my computer right now)

**Comment by doronz88** [comment]
Actually the better and cross-arch solution is to use Hilda's `expr = {'$arg1': 'po', ...}`
The new PR uses this solution instead
